version: '3.9'

services:
  used_furniture:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: used_furniture
    environment:
      - SSL_REQUIRED=true
      - PROXY_ADDRESS_FORWARDING=true
      - EXTERNAL_URL=casademoveisusados.com
      - INTERNAL_ACCESS_PORT=80

networks:
  default:
    external:
      name: terrabyte_network
